name: Build Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_cli_macos:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: build Maui.Dogfood.Cli.csproj
        run: dotnet build ${{ vars.GITHUB_WORKSPACE }}/src/Maui.Dogfood.Cli/Maui.Dogfood.Cli.csproj

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ${{ vars.GITHUB_WORKSPACE }}/src/Maui.Dogfood.Cli/bin
